# Generated by Django 3.2.8 on 2021-11-08 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('mainText', models.TextField(verbose_name='Описание')),
                ('timeDate', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='RunPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название тренировки')),
                ('link_post', models.TextField(verbose_name='Ссылка на пост в Strava')),
                ('distance', models.CharField(max_length=15, verbose_name='Дистанция')),
                ('run_time', models.CharField(max_length=20, verbose_name='Итоговое время')),
                ('date_running', models.CharField(max_length=30, verbose_name='Дата тренировки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(verbose_name='Дата рождения (DD.MM.YYYY)')),
                ('megafaculty', models.CharField(max_length=30, verbose_name='Мегафакультет')),
                ('group', models.CharField(max_length=10, verbose_name='Номер группы')),
                ('info', models.TextField(verbose_name='Дополнительная нформация')),
                ('num_visits', models.CharField(max_length=1, verbose_name='Количество визитов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
